import Head from 'next/head';
import Image from 'next/image';
import { David_Libre, Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar.js';
import Main from '../components/Main.js';
import Hire from '../components/Hire.js';
import Footer from '../components/Footer.js';

// import lottie from "lottie-react";
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    
    <div id='root'>

      
     <Head>
        <title>I dey learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/split-type"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"></script>
      
      </Head> 
    <Navbar/>
    <Main/>
    {/* <Hire/> */}
    <div>

    <Footer/>
    </div>
{

}   
    
  
    </div>
  )
}
